//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JalkahoitolaDemoEntities : DbContext
    {
        public JalkahoitolaDemoEntities()
            : base("name=JalkahoitolaDemoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bandage> Bandages { get; set; }
        public virtual DbSet<Cream> Creams { get; set; }
        public virtual DbSet<Glove> Gloves { get; set; }
        public virtual DbSet<ItemGroupName> ItemGroupNames { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
