//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Glove
    {
        public Nullable<int> ItemGroupID { get; set; }
        public string ProductName__FK_ { get; set; }
        public Nullable<decimal> Prices { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<System.DateTime> Exp_Date_ { get; set; }
        public int ItemSubGroubID { get; set; }
    
        public virtual ItemGroupName ItemGroupName { get; set; }
    }
}
